django_app_product_price_heroku/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product_price.urls')),
    path('', include('django.contrib.auth.urls')),
]

product_price/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'product_price'
urlpatterns = [
    path('', views.index_product, name='index_product'),
    path('signup', views.signup, name='signup'),
    path('add', views.add_product, name='add_product'),
    path('login/', auth_views.LoginView.as_view(template_name='product_price/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='product_price/logout.html'), name='logout'),
]

product_price/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=5, decimal_places=2, default='')
    store = models.CharField(max_length=20, default='')

    def __str__(self):
        return self.name

product_price/forms.py
from django import forms
from .models import Product


class AddProductForms(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'store']

product_price/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from .models import Product
from django.contrib.auth.forms import UserCreationForm
from .forms import AddProductForms
from django.contrib import messages


def index_product(request):
    all_products = Product.objects.order_by('name')
    return render(request, 'product_price/product.html', {'all_products': all_products})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'product_price/product.html')
    else:
        form = UserCreationForm()
        return render(request, 'product_price/signup.html', {'form': form})


def add_product(request):
    form = AddProductForms(request.POST or None)
    if form.is_valid():
        form.save()
        form = AddProductForms()
        messages.success(request, f'Artykuł dodany')
        return render(request, 'product_price/add_product.html', {'form': form})

    return render(request, 'product_price/add_product.html', {'form': form})

product_price/templates/product_price/add_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Product</title>
    <link rel="stylesheet" type="text/css" href="{% static 'product_price/style.css' %}">

</head>
<body>

    <p class="title-product">Add Product</p>
    <a href="{% url 'product_price:index_product' %}">Home</a>
    <br>

    <form method="POST">
        {% csrf_token %}

        <input id="id_name" type="text" name="name" placeholder="Product">
        <input id="id_price" type="number" name="price" placeholder="Price">
        <input id="id_store" type="text" name="store" placeholder="Store">
        <input class="button" type="submit" name="" value="Add Product">

    </form>
    <br>
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}

</body>
</html>

product_price/templates/product_price/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css"
          href="{% static 'product_price/style.css' %}">
</head>
<body>

        {% if user.is_authenticated %}
            <div  class="nav">
            <a href="{% url 'product_price:add_product' %}">Dodaj Produkt</a>
            <a href="{% url 'product_price:logout' %}">Wyloguj</a>
            </div>
            {% block content %}{% endblock%}

        {% else %}
            <div class="nav">
                <a href="{% url 'product_price:login' %}">Zaloguj</a>
                <a href="{% url 'product_price:signup' %}">Rejestracja</a>
            </div>
        {% endif %}




</body>
</html>

product_price/templates/product_price/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css"
          href="{% static 'product_price/style.css' %}">
</head>
<body>

    <form method="POST" >
        {% csrf_token %}
            <input id="id_username" type="text" name="username" placeholder="Username">
            <input id="id_password" type="password" name="password" placeholder="Password">
            <input class="button" type="submit" name="" value="Login">
    </form>

</body>
</html>

product_price/templates/product_price/logout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
    <link rel="stylesheet" type="text/css"
          href="{% static 'product_price/style.css' %}">
</head>
<body>
    <p class="p-logout">Zostałeś poprawnie wylogowany</p>
    <a class="a-logout" href="{% url 'product_price:login' %}">Login</a>
</body>
</html>

product_price/templates/product_price/product.html
{% extends "product_price/layout.html" %}

    <title>Index_info</title>

{% block content %}

            <table>
                {% if all_products %}
                {% for product in all_products %}
                <tr>
                    <td>{{ product }}</td>
                    <td>{{ product.price }}</td>
                    <td>{{ product.store }}</td>
                </tr>
                {% endfor %}
                {% endif %}
            </table>

{% endblock content %}

product_price/templates/product_price/signup.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Signup</title>
    <link rel="stylesheet" type="text/css"
          href="{% static 'product_price/style.css' %}">
</head>
<body>

    <form method="POST">
        {% csrf_token %}
        <input id="id_username" type="text" name="username" placeholder="Username">
        <input id="id_password1" type="password" name="password1" placeholder="Password">
        <input id="id_password2" type="password" name="password2" placeholder="Password">
        <input class="button" type="submit" value="Signup">
    </form>

</body>
</html>